name: Test


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  flake8:
    name: 'Lint with Flake8'
    runs-on: ubuntu-latest
    steps:
      - name: Install flake8
      - uses: actions/checkout@v2
        run: |
          sudo python3 -m pip install flake8
      - name: Run flake8
        run: flake8

  black:
    name: 'Lint with black'
    runs-on: ubuntu-latest
    steps:
      - name: Install black
      - uses: actions/checkout@v2
        run: |
          sudo python3 -m pip install black
      - name: Run black
        run: black --check --diff

  pytest:
    name: 'Test with Pytest'
    runs-on: ubuntu-latest
    steps:
      - name: Install pytest
      - uses: actions/checkout@v2
        run: |
          sudo python3 -m pip install pytest
      - name: Run pytest
        run: pytest
