name: Test


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - name: flake8
            run: flake8
          - name: black
            run: black --check --diff
          - name: pytest
            run: pytest

    name: ${{ matrix.tool.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Install ${{ matrix.tool.name }}
        run: python3 -m pip install ${{ matrix.tool.name }}
      - name: Run ${{ matrix.tool.name }}
        run: ${{ matrix.tool.run }}
